spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/auth/realms/dacs}

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic
      apiconectorclient:
        url: '${MS_CONECTOR_URL:http://localhost:9002/conector}'
      apiBackendClient:
        url: '${MS_BACKEND_URL:http://localhost:9003/backend}'
      apiBackendPacientesClient:
        url: '${MS_BACKEND_URL:http://localhost:9003/backend}'
      apiBackendCirugiasClient:
        url: '${MS_BACKEND_URL:http://localhost:9003/backend}'
      apiBackendQuirofanoClient:
        url: '${MS_BACKEND_URL:http://localhost:9003/backend}'
      apiBackendPersonalClient:
        url: '${MS_BACKEND_URL:http://localhost:9003/backend}'

management:
  endpoints:
    web:
      base-path: /metrics
      exposure:
        include: "health,info"

logging:
  level:
    "[org.springframework.security]": DEBUG
    "[org.springframework.security.oauth2]": DEBUG
    "[com.dacs.bff.config.JwtTokenInterceptor]": DEBUG

server:
  port: 9001
  servlet:
    contextPath: /bff
